# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Category.destroy_all
Monument.destroy_all
Beacon.destroy_all
Poi.destroy_all

@u1 = User.create(email:'teste@teste.pt',password:'123456')

@c1 = Category.create(name:'Capelas')
@c2 = Category.create(name:'Igrejas')
@c3 = Category.create(name:'Museus')
@c4 = Category.create(name:'LocaisInteresse')

@b1 = Beacon.create(uuid:'1',manufacturer:'cisco',battery:'22-04-2017')
@b2 = Beacon.create(uuid:'2',manufacturer:'cisco',battery:'23-04-2017')
@b3 = Beacon.create(uuid:'3',manufacturer:'cisco',battery:'22-04-2017')
@b4 = Beacon.create(uuid:'4',manufacturer:'cisco',battery:'23-04-2017')
@b5 = Beacon.create(uuid:'5',manufacturer:'cisco',battery:'22-04-2017')
@b6 = Beacon.create(uuid:'6',manufacturer:'cisco',battery:'23-04-2017')
@b7 = Beacon.create(uuid:'7',manufacturer:'cisco',battery:'22-04-2017')
@b8 = Beacon.create(uuid:'8',manufacturer:'cisco',battery:'23-04-2017')
@b9 = Beacon.create(uuid:'9',manufacturer:'cisco',battery:'22-04-2017')
@b10 = Beacon.create(uuid:'10',manufacturer:'cisco',battery:'23-04-2017')
@b11 = Beacon.create(uuid:'11',manufacturer:'cisco',battery:'22-04-2017')
@b12 = Beacon.create(uuid:'12',manufacturer:'cisco',battery:'23-04-2017')
@b13 = Beacon.create(uuid:'13',manufacturer:'cisco',battery:'22-04-2017')
@b14 = Beacon.create(uuid:'14',manufacturer:'cisco',battery:'23-04-2017')
@b15 = Beacon.create(uuid:'15',manufacturer:'cisco',battery:'22-04-2017')
@b16 = Beacon.create(uuid:'16',manufacturer:'cisco',battery:'23-04-2017')
@b17 = Beacon.create(uuid:'17',manufacturer:'cisco',battery:'22-04-2017')
@b18 = Beacon.create(uuid:'18',manufacturer:'cisco',battery:'23-04-2017')
@b19 = Beacon.create(uuid:'19',manufacturer:'cisco',battery:'22-04-2017')
@b20 = Beacon.create(uuid:'20',manufacturer:'cisco',battery:'23-04-2017')


# @m1 = Monument.create(name:'Capela de Santa Iria',description:'A igreja da lendária padroeira de Tomar contém um admirável calvário em pedra e uma profusa decoração alusiva aos símbolos do Espírito Santo no apainelado da Capela-Mor. A linguagem da Renascença Coimbrã é realçada pelo pórtico e pela janela ao gosto de Nicolau Chanterène. Interiormente é revestida por azulejos ponta de diamante, do século XVII. O retábulo de Cristo crucificado é atribuído a João de Ruão. O Arco das freiras é a passagem aérea entre as Freiras Clarissas do Convento de Santa Iria e o antigo Palácio de Frei António de Lisboa.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/Capela%20sta%20Iria.jpg',longitude:'39.604502',latitude:'-8.410383',address:'rua', category:@c1)
# @m2 = Monument.create(name:'Capela de São Gregório',description:'Construção quinhentista de planta circular dedicada a S. Gregório Nazianzeno, teólogo que provou a divindade de Jesus. Destaca-se o portal manuelino rectangular, sobriamente decorado e abrigado pela galilé que circunda três lados da capela. Os painéis de azulejos setecentistas são originários do Convento das Trinas de Lisboa.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/s.%20gregorio.jpg',longitude:'39.607028',latitude:'-8.415000',address:'rua', category:@c1)
# @m3 = Monument.create(name:'Capela de Nossa Senhora da Conceição',description:'Pequena igreja basilical de três naves destinada a capela funerária de D. João III, o rei que ordenou a sua construção em 1547. Concebido por João de Castilho, este belo exemplar do classicismo italiano é a melhor evocação da arte greco-romana na Península Ibérica. Destaca-se a implementação urbana florentina, a sobriedade austera das proporções, as janelas perspectivadas segundo a orientação solar e, no interior, a articulação dos volumes entre as naves e o transepto, a vibração dramática da iluminação natural e a decoração coríntia dos capitéis.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/sra.%20conceicao%201.jpg',longitude:'39.605917',latitude:'-8.416806',address:'rua', category:@c1)
# @m4 = Monument.create(name:'Capela de São Lourenço',description:'A 10 de Agosto de 1385, dia do mártir S. Lourenço, as hostes de D. João I juntaram-se neste local, às do Condestável D. Nuno Álvares Pereira, rumo a Aljubarrota.  A Capela e o Padrão assinalam o encontro e o santo, orago da ermida, deu o nome ao lugar. Aires de Quental, encarregado de ali construir uma fábrica de armas, por D. Manuel, foi o edificador da Capela.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/s.%20lourenco.jpg',longitude:'39.592056',latitude:'-8.405722',address:'rua', category:@c1)
# @m5 = Monument.create(name:'Capela da Nossa Senhora da Piedade',description:'Ermida da Senhora da Piedade ou do Monte mandada edificar pelo Alcaide de Óbidos no século XIV. Ao portal em ogiva acede-se por uma galilé alpendrada. Foi restaurada e modificada em 1613 pelo juiz do povo Bernardo Ortiz Ochoa. Os azulejos azuis e brancos enxaquetados são século XVII, e o terraço e a escadaria de meados do século XIX.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/Sra.Piedade%204.jpg',longitude:'39.610619',latitude:'-8.415520',address:'rua', category:@c1)
# @m6 = Monument.create(name:'Capela de Santo António',description:'Foi construída entre 1953 e 1955, mas contém elementos arquitetonicos de uma ermida renascentista cinco Séculos mais antiga - a Capela do Casal de Santo António, provavelmente de 1459, existente  perto do Aqueduto dos Pegões. Em 1924, sob a égide da União dos Amigos dos Monumentos da Ordem de Cristo, procedeu-se ao desmantelamento controlado das cantarias da capela. Em 1953, com a construção de um Bairro Social (hoje, 1º de Maio), edificou-se a capela atual com elementos arquitetónicos da original: portal principal e a capela-mor com nervuras. Entretanto, a União dos Amigos da Ordem de Cristo cedeu, do espólio de outras edifições demolidas, mais alguns elementos para enriquecer a obra: a rosácea, os sobrearcos das portas, as canmtarias renascença da porta de serviço e os azulejos hispano-árabes do altar provenientes da chaminé de um antigo prédio da Praça da República.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/s.%20antonio%201.jpg',longitude:'39.608320',latitude:'-8.406862',address:'rua', category:@c1)
# @m7 = Monument.create(name:'Igreja de Santa Maria do Olival',description:'Templo gótico de meados do século XIII construído no sítio da antiga igreja templária erguida por D. Gualdim. O Panteão dos Mestres Templários foi sede de nullius diocesis com jurisdição sobre as igrejas dos Descobrimentos. A interessante estrutura espacial de três naves serviu de modelo à igreja de São João Baptista e a outras igrejas do gótico final português. No exterior, destaca-se a magnífica rosácea, a torre de atalaia adaptada a campanário, e a loggia do século XVI; no interior, a lápide de Gualdim Pais, o túmulo de D. Diogo Pinheiro e as imagens Nossa Senhora do Leite e Santas Mães.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/s.%20m.%20olival%201.jpg',longitude:'39.601500',latitude:'-8.407278',address:'rua', category:@c2)
# @m8 = Monument.create(name:'Igreja de São João Baptista',description:'Templo de estilo gótico tardio, construído por ordem de D. Manuel I sobre anterior ermida da mesma evocação. Foi concluído no início do século XVI. A simbólica de D, Manuel (Brasão Real, Esfera Armilar e Cruz de Cristo) está presente na torre e repete-se no púlpito e nos portais Poente e Norte. No exterior destaca-se a Torre de três corpos, o Portal Principal, o Portal Norte e o Portal Sul, verosímil memória de um templo primitivo. A estrutura espacial das naves é idêntica à da igreja de Santa Maria do Olival, enriquecida pelo púlpito da pedra lavrada e pela pintura quinhentista, expoente máximo da arte pictórica portuguesa do século XVI.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/s.%20joao.jpg',longitude:'39.603639',latitude:'-8.414556',address:'rua', category:@c2)
# @m9 = Monument.create(name:'Igreja da Nossa Senhora da Graça',description:'A Misericórdia de Tomar foi fundada pelo Rei D. Manuel I, em 1510. A Igreja de Nossa Senhora da Graça, ou de Nossa Senhora da Cadeia é vulgarmente conhecida por Misericórdia. É uma construção maneirista edificada na segunda metade do século XVI. A imagem da padroeira preenche o nicho que remata o elegante pórtico Quinhentista. A nave é decorada por molduras rectangulares de pedra e azulejos enxaquetados.  Realce para o Milagre Eucarístico de Santo António, em painel do século XVI. O Hospital substituiu o de Nossa Senhora da Graça (século XV) resultante da unificação henriquina de todos os hospitais e hospícios que havia na Vila.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/n.%20sra.%20graca.jpg',longitude:'39.602102',latitude:'-8.413937',address:'rua', category:@c2)
# @m10 = Monument.create(name:'Igreja e Convento de São Francisco',description:'O Convento de São Francisco é um edifício maneirista construído em torno de dois claustros.  Em meados do século XVII substituiu a capela de Nossa Senhora dos Anjos. Acolheu a comunidade da então extinta casa de Santa Cita.  Templo do século XVII (1625-1660), característico da Arquitectura Chã. A fachada destaca o maneirismo do portal e do frontispício. No interior, de uma só nave coberta a grande altura por uma abóbada de berço, realçam-se as esculturas de um raríssimo Calvário e as quatro representações pictóricas da Vida da Virgem. Na primeira capela do lado do Evangelho sobressai a imagem de Santa Iria, padroeira da cidade de Tomar.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/s._francisco%201.jpg',longitude:'39.600306',latitude:'-8.414389',address:'rua', category:@c2)
# @m11 = Monument.create(name:'Museu dos Fósforos',description:'No Convento de S. Francisco conserva-se uma coleção superior 80.000 caixas, etiquetas e carteiras de fósforos doada por Aquiles da Mota à Câmara em 1980. A coleção nasceu com uma troca de caixas entre Mota Lima e uma senhora americana durante uma viagem marítima, quando se dirigiam a Londres para a cerimónia da Coroação da Rainha Isabel II.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/fsforos2web.jpg',longitude:'39.599730',latitude:'-8.413967',address:'rua', category:@c3)
# @m12 = Monument.create(name:'Museu Municipal - Núcleo de Arte Contemporânea',description:'O Núcleo de Arte Contemporânea foi criado em 2004, por doação do Professor José-Augusto França. O conjunto de pinturas, esculturas, desenhos e fotografias abrange um arco cronológico que se estende de 1932 à atualidade. Obras de Mário Eloy, Júlio e Almada Negreiros, assinalam o Modernismo do segundo quartel do século XX. O Surrealismo tem um lugar de destaque com um significativo número de trabalhos, produzidos a partir do Grupo Surrealista de Lisboa, onde se contam nomes como António Pedro, Vespeira, Fernando de Azevedo ou Fernando Lemos. O Abstraccionismo e a eclosão da Nova-Figuração estão igualmente representados com obras de Fernando Lanhas, João Cutileiro, Joaquim Rodrigo, Noronha da Costa, entre outros. Completa a coleção, a variada produção que marca o final do século até aos dias de hoje.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/NAC3%20web.jpg',longitude:'39.604697',latitude:'-8.413725',address:'rua', category:@c3)
# @m13 = Monument.create(name:'Museu Luso-Hebraico Abraão Zacuto (Sinagoga)',description:'Está instalado na Sinagoga. O acervo é constituído por lápides funerárias, objetos relacionados com Cultura Judaica e alfaias religiosas. Escavações na sala anexa deram a conhecer moedas, cerâmica de uso doméstico e o sistema de aquecimento de água para o banho Mikva.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/Museu%20hebraico%202%20web.jpg',longitude:'39.603279',latitude:'-8.413806',address:'rua', category:@c3)
# @m14 = Monument.create(name:'Casa Memória Lopes-Graça',description:'Sem informação.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/cmlg.JPG',longitude:'39.603588',latitude:'-8.412452',address:'rua', category:@c3)
# @m15 = Monument.create(name:'Paços do Concelho',description:'Antigos Paços Reais que D. Manuel I edificou e ofereceu à Câmara. A remodelação maneirista do século XVI eliminou a decoração manuelina. Permanecem os símbolos do Rei Venturoso: Brasão Real, Esfera Armilar e Cruz de Cristo, já com adaptação Filipina. Destaca-se a galilé de três arcos, a fachada posterior em arcos de volta inteira e, no interior, a galeria de exposições (memória das Boticas do Infante D. Henrique) e o Salão Nobre, com um antigo Brasão de Tomar no tecto em masseira.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/camara.png',longitude:'39.603565',latitude:'-8.415003',address:'rua', category:@c4)
# @m16 = Monument.create(name:'Edifício do Turismo',description:'De 1933, com projeto de José Vilaça, tem elementos escultóricos, arquitetónicos e azulejares dos Séc. XV e XVI provenientes de edifícios antigos da cidade. Tido como o mais antigo Posto de Turismo do País, alberga ainda obras de Francesco Bartolozzi (azulejos), Ricardo Leone (vitrais) e belíssimos trabalhos neo-renascentista da casa Sousa Braga.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/pt.png',longitude:'39.601613',latitude:'-8.415664',address:'rua', category:@c4)
# @m17 = Monument.create(name:'Casa dos Cubos',description:'O Projeto previa a reconversão de uma infraestrutura desativada, de particular relevância social e económica no tecido urbano da cidade de Tomar. Situado no centro histórico, junto às margens do rio Nabão, o edifício foi sujeito ao longo dos tempos a sucessivas aderências e alterações, encontrando-se ameaçado por alguma decadência e desajustado à utilização pretendida. Originalmente concebido como casa de armazenamento e contagem de produtos agrícolas sob forma de pagamento de rendas às ordens religiosas, foi buscar a sua denominação às antigas medidas de capacidade, o alqueire e o almude, à época correntemente designados como “cubos”. Posteriormente adaptado a edifício de escritórios das antigas Fábricas Mendes Godinho, sobreviveu aos tempos readquirindo no âmbito do Programa Polis um novo papel na cidade: o de Centro de Monitorização e Interpretação Ambiental. O programa preliminar constituía-se por duas partes distintas, uma de carácter público composta por um espaço expositivo lúdico-pedagógico e outra de carácter privado composta por salas de formação e residências artísticas. No confronto com os regulamentos, a proposta mantém a construção existente na totalidade do seu perímetro exterior, sendo o interior inteiramente despojado de todo o seu “miolo”. Assim e perante a condição programática a nova construção estabelece-se como a estrutura anatómica da pré-existência. Os espaços que necessitavam de recolhimento são definidos volumetricamente surgindo claramente reconhecíveis e otimizados na sua habitabilidade, cada um com a sua atmosfera, identidade, forma, dimensão e uso. As restantes atividades inserem-se no vazio espacial do edifício existente e são caracterizadas através dos acontecimentos programáticos definidos pelos espaços encerrados.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/casa_cubos.jpg',longitude:'39.602367',latitude:'-8.411440',address:'rua', category:@c4)
# @m18 = Monument.create(name:'Aqueduto dos Pegões Altos',description:'Foi mandado construir por Filipe I, para abastecimento do Convento de Cristo. Em 1593, Filipe Terzi iniciou os trabalhos e Pedro Fernandes Torres concluí-los-ia em 1613. Com 6 quilómetros de extensão e 180 arcos, forma, no troço de maior desnível, ao Vale de Pegões, duas filas de arcos sobrepostas em que a arcaria de volta inteira superior repousa nos arcos ogivados inferiores.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/Aqueduto%20dos%20Peges%20web.jpg',longitude:'39.608552',latitude:'-8.439092',address:'rua', category:@c4)
# @m19 = Monument.create(name:'Estaus',description:'O edifício, onde funcionou o antigo bazar dos judeus foi encomendado pelo Infante D. Henrique para sua aposentadoria, alojamento e comércio. A complexa construção de dezasseis arcos em ogiva nos dois lados da rua nunca foi concluída.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/Estaus.jpg',longitude:'39.602247',latitude:'-8.411906',address:'rua', category:@c4)
# @m20 = Monument.create(name:'Levada de Tomar',description:'Sob a designação de Levada de Tomar, identificamos um conjunto edificado com um relevante horizonte cronológico, desde o período medieval, passando pela época moderna, até à época contemporânea.A sua origem remonta aos finais do século XII e, com uma sucessão complexa de contextos espaciais e tecnológicos, a sua actividade de carácter industrial manteve-se até finais do século XX  (e, numa das unidades oficinais daquele conjunto, manteve-se até ao início do século XXI).',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/levada_nuno_miguel_queiroz.jpg',longitude:'39.603618',latitude:'-8.411616',address:'rua', category:@c4)





# @p1 = Poi.create(name:'Capela de Santa Iria',description:'A igreja da lendária padroeira de Tomar contém um admirável calvário em pedra e uma profusa decoração alusiva aos símbolos do Espírito Santo no apainelado da Capela-Mor. A linguagem da Renascença Coimbrã é realçada pelo pórtico e pela janela ao gosto de Nicolau Chanterène. Interiormente é revestida por azulejos ponta de diamante, do século XVII. O retábulo de Cristo crucificado é atribuído a João de Ruão. O Arco das freiras é a passagem aérea entre as Freiras Clarissas do Convento de Santa Iria e o antigo Palácio de Frei António de Lisboa.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/Capela%20sta%20Iria.jpg',longitude:'39.604502',latitude:'-8.410383',monument:@m1, beacon:@b1)
# @p2 = Poi.create(name:'Capela de São Gregório',description:'Construção quinhentista de planta circular dedicada a S. Gregório Nazianzeno, teólogo que provou a divindade de Jesus. Destaca-se o portal manuelino rectangular, sobriamente decorado e abrigado pela galilé que circunda três lados da capela. Os painéis de azulejos setecentistas são originários do Convento das Trinas de Lisboa.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/s.%20gregorio.jpg',longitude:'39.607028',latitude:'-8.415000',monument:@m2, beacon:@b2)
# @p3 = Poi.create(name:'Capela de Nossa Senhora da Conceição',description:'Pequena igreja basilical de três naves destinada a capela funerária de D. João III, o rei que ordenou a sua construção em 1547. Concebido por João de Castilho, este belo exemplar do classicismo italiano é a melhor evocação da arte greco-romana na Península Ibérica. Destaca-se a implementação urbana florentina, a sobriedade austera das proporções, as janelas perspectivadas segundo a orientação solar e, no interior, a articulação dos volumes entre as naves e o transepto, a vibração dramática da iluminação natural e a decoração coríntia dos capitéis.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/sra.%20conceicao%201.jpg',longitude:'39.605917',latitude:'-8.416806',monument:@m3, beacon:@b3)
# @p4 = Poi.create(name:'Capela de São Lourenço',description:'A 10 de Agosto de 1385, dia do mártir S. Lourenço, as hostes de D. João I juntaram-se neste local, às do Condestável D. Nuno Álvares Pereira, rumo a Aljubarrota.  A Capela e o Padrão assinalam o encontro e o santo, orago da ermida, deu o nome ao lugar. Aires de Quental, encarregado de ali construir uma fábrica de armas, por D. Manuel, foi o edificador da Capela.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/s.%20lourenco.jpg',longitude:'39.592056',latitude:'-8.405722',monument:@m4, beacon:@b4)
# @p5 = Poi.create(name:'Capela da Nossa Senhora da Piedade',description:'Ermida da Senhora da Piedade ou do Monte mandada edificar pelo Alcaide de Óbidos no século XIV. Ao portal em ogiva acede-se por uma galilé alpendrada. Foi restaurada e modificada em 1613 pelo juiz do povo Bernardo Ortiz Ochoa. Os azulejos azuis e brancos enxaquetados são século XVII, e o terraço e a escadaria de meados do século XIX.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/Sra.Piedade%204.jpg',longitude:'39.610619',latitude:'-8.415520',monument:@m5, beacon:@b5)
# @p6 = Poi.create(name:'Capela de Santo António',description:'Foi construída entre 1953 e 1955, mas contém elementos arquitetonicos de uma ermida renascentista cinco Séculos mais antiga - a Capela do Casal de Santo António, provavelmente de 1459, existente  perto do Aqueduto dos Pegões. Em 1924, sob a égide da União dos Amigos dos Monumentos da Ordem de Cristo, procedeu-se ao desmantelamento controlado das cantarias da capela. Em 1953, com a construção de um Bairro Social (hoje, 1º de Maio), edificou-se a capela atual com elementos arquitetónicos da original: portal principal e a capela-mor com nervuras. Entretanto, a União dos Amigos da Ordem de Cristo cedeu, do espólio de outras edifições demolidas, mais alguns elementos para enriquecer a obra: a rosácea, os sobrearcos das portas, as canmtarias renascença da porta de serviço e os azulejos hispano-árabes do altar provenientes da chaminé de um antigo prédio da Praça da República.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/s.%20antonio%201.jpg',longitude:'39.608320',latitude:'-8.406862',monument:@m6, beacon:@b6)
# @p7 = Poi.create(name:'Igreja de Santa Maria do Olival',description:'Templo gótico de meados do século XIII construído no sítio da antiga igreja templária erguida por D. Gualdim. O Panteão dos Mestres Templários foi sede de nullius diocesis com jurisdição sobre as igrejas dos Descobrimentos. A interessante estrutura espacial de três naves serviu de modelo à igreja de São João Baptista e a outras igrejas do gótico final português. No exterior, destaca-se a magnífica rosácea, a torre de atalaia adaptada a campanário, e a loggia do século XVI; no interior, a lápide de Gualdim Pais, o túmulo de D. Diogo Pinheiro e as imagens Nossa Senhora do Leite e Santas Mães.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/s.%20m.%20olival%201.jpg',longitude:'39.601500',latitude:'-8.407278',monument:@m7, beacon:@b7)
# @p8 = Poi.create(name:'Igreja de São João Baptista',description:'Templo de estilo gótico tardio, construído por ordem de D. Manuel I sobre anterior ermida da mesma evocação. Foi concluído no início do século XVI. A simbólica de D, Manuel (Brasão Real, Esfera Armilar e Cruz de Cristo) está presente na torre e repete-se no púlpito e nos portais Poente e Norte. No exterior destaca-se a Torre de três corpos, o Portal Principal, o Portal Norte e o Portal Sul, verosímil memória de um templo primitivo. A estrutura espacial das naves é idêntica à da igreja de Santa Maria do Olival, enriquecida pelo púlpito da pedra lavrada e pela pintura quinhentista, expoente máximo da arte pictórica portuguesa do século XVI.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/s.%20joao.jpg',longitude:'39.603639',latitude:'-8.414556',monument:@m8, beacon:@b8)
# @p9 = Poi.create(name:'Igreja da Nossa Senhora da Graça',description:'A Misericórdia de Tomar foi fundada pelo Rei D. Manuel I, em 1510. A Igreja de Nossa Senhora da Graça, ou de Nossa Senhora da Cadeia é vulgarmente conhecida por Misericórdia. É uma construção maneirista edificada na segunda metade do século XVI. A imagem da padroeira preenche o nicho que remata o elegante pórtico Quinhentista. A nave é decorada por molduras rectangulares de pedra e azulejos enxaquetados.  Realce para o Milagre Eucarístico de Santo António, em painel do século XVI. O Hospital substituiu o de Nossa Senhora da Graça (século XV) resultante da unificação henriquina de todos os hospitais e hospícios que havia na Vila.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/n.%20sra.%20graca.jpg',longitude:'39.602102',latitude:'-8.413937',monument:@m9, beacon:@b9)
# @p10 = Poi.create(name:'Igreja e Convento de São Francisco',description:'O Convento de São Francisco é um edifício maneirista construído em torno de dois claustros.  Em meados do século XVII substituiu a capela de Nossa Senhora dos Anjos. Acolheu a comunidade da então extinta casa de Santa Cita.  Templo do século XVII (1625-1660), característico da Arquitectura Chã. A fachada destaca o maneirismo do portal e do frontispício. No interior, de uma só nave coberta a grande altura por uma abóbada de berço, realçam-se as esculturas de um raríssimo Calvário e as quatro representações pictóricas da Vida da Virgem. Na primeira capela do lado do Evangelho sobressai a imagem de Santa Iria, padroeira da cidade de Tomar.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/Visitar/s._francisco%201.jpg',longitude:'39.600306',latitude:'-8.414389',monument:@m10, beacon:@b10)
# @p11 = Poi.create(name:'Museu dos Fósforos',description:'No Convento de S. Francisco conserva-se uma coleção superior 80.000 caixas, etiquetas e carteiras de fósforos doada por Aquiles da Mota à Câmara em 1980. A coleção nasceu com uma troca de caixas entre Mota Lima e uma senhora americana durante uma viagem marítima, quando se dirigiam a Londres para a cerimónia da Coroação da Rainha Isabel II.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/fsforos2web.jpg',longitude:'39.599730',latitude:'-8.413967',monument:@m11, beacon:@b11)
# @p12 = Poi.create(name:'Museu Municipal - Núcleo de Arte Contemporânea',description:'O Núcleo de Arte Contemporânea foi criado em 2004, por doação do Professor José-Augusto França. O conjunto de pinturas, esculturas, desenhos e fotografias abrange um arco cronológico que se estende de 1932 à atualidade. Obras de Mário Eloy, Júlio e Almada Negreiros, assinalam o Modernismo do segundo quartel do século XX. O Surrealismo tem um lugar de destaque com um significativo número de trabalhos, produzidos a partir do Grupo Surrealista de Lisboa, onde se contam nomes como António Pedro, Vespeira, Fernando de Azevedo ou Fernando Lemos. O Abstraccionismo e a eclosão da Nova-Figuração estão igualmente representados com obras de Fernando Lanhas, João Cutileiro, Joaquim Rodrigo, Noronha da Costa, entre outros. Completa a coleção, a variada produção que marca o final do século até aos dias de hoje.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/NAC3%20web.jpg',longitude:'39.604697',latitude:'-8.413725',monument:@m12, beacon:@b12)
# @p13 = Poi.create(name:'Museu Luso-Hebraico Abraão Zacuto (Sinagoga)',description:'Está instalado na Sinagoga. O acervo é constituído por lápides funerárias, objetos relacionados com Cultura Judaica e alfaias religiosas. Escavações na sala anexa deram a conhecer moedas, cerâmica de uso doméstico e o sistema de aquecimento de água para o banho Mikva.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/Museu%20hebraico%202%20web.jpg',longitude:'39.603279',latitude:'-8.413806',monument:@m13, beacon:@b13)
# @p14 = Poi.create(name:'Casa Memória Lopes-Graça',description:'Sem informação.',image:'http://www.cm-tomar.pt/images/CMT/visitar/imagens/cmlg.JPG',longitude:'39.603588',latitude:'-8.412452',monument:@m14, beacon:@b14)
# @p15 = Poi.create(name:'Paços do Concelho',description:'Antigos Paços Reais que D. Manuel I edificou e ofereceu à Câmara. A remodelação maneirista do século XVI eliminou a decoração manuelina. Permanecem os símbolos do Rei Venturoso: Brasão Real, Esfera Armilar e Cruz de Cristo, já com adaptação Filipina. Destaca-se a galilé de três arcos, a fachada posterior em arcos de volta inteira e, no interior, a galeria de exposições (memória das Boticas do Infante D. Henrique) e o Salão Nobre, com um antigo Brasão de Tomar no tecto em masseira.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/camara.png',longitude:'39.603565',latitude:'-8.415003',monument:@m15, beacon:@b15)
# @p16 = Poi.create(name:'Edifício do Turismo',description:'De 1933, com projeto de José Vilaça, tem elementos escultóricos, arquitetónicos e azulejares dos Séc. XV e XVI provenientes de edifícios antigos da cidade. Tido como o mais antigo Posto de Turismo do País, alberga ainda obras de Francesco Bartolozzi (azulejos), Ricardo Leone (vitrais) e belíssimos trabalhos neo-renascentista da casa Sousa Braga.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/pt.png',longitude:'39.601613',latitude:'-8.415664',monument:@m16, beacon:@b16)
# @p17 = Poi.create(name:'Casa dos Cubos',description:'O Projeto previa a reconversão de uma infraestrutura desativada, de particular relevância social e económica no tecido urbano da cidade de Tomar. Situado no centro histórico, junto às margens do rio Nabão, o edifício foi sujeito ao longo dos tempos a sucessivas aderências e alterações, encontrando-se ameaçado por alguma decadência e desajustado à utilização pretendida. Originalmente concebido como casa de armazenamento e contagem de produtos agrícolas sob forma de pagamento de rendas às ordens religiosas, foi buscar a sua denominação às antigas medidas de capacidade, o alqueire e o almude, à época correntemente designados como “cubos”. Posteriormente adaptado a edifício de escritórios das antigas Fábricas Mendes Godinho, sobreviveu aos tempos readquirindo no âmbito do Programa Polis um novo papel na cidade: o de Centro de Monitorização e Interpretação Ambiental. O programa preliminar constituía-se por duas partes distintas, uma de carácter público composta por um espaço expositivo lúdico-pedagógico e outra de carácter privado composta por salas de formação e residências artísticas. No confronto com os regulamentos, a proposta mantém a construção existente na totalidade do seu perímetro exterior, sendo o interior inteiramente despojado de todo o seu “miolo”. Assim e perante a condição programática a nova construção estabelece-se como a estrutura anatómica da pré-existência. Os espaços que necessitavam de recolhimento são definidos volumetricamente surgindo claramente reconhecíveis e otimizados na sua habitabilidade, cada um com a sua atmosfera, identidade, forma, dimensão e uso. As restantes atividades inserem-se no vazio espacial do edifício existente e são caracterizadas através dos acontecimentos programáticos definidos pelos espaços encerrados.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/casa_cubos.jpg',longitude:'39.602367',latitude:'-8.411440',monument:@m17, beacon:@b17)
# @p18 = Poi.create(name:'Aqueduto dos Pegões Altos',description:'Foi mandado construir por Filipe I, para abastecimento do Convento de Cristo. Em 1593, Filipe Terzi iniciou os trabalhos e Pedro Fernandes Torres concluí-los-ia em 1613. Com 6 quilómetros de extensão e 180 arcos, forma, no troço de maior desnível, ao Vale de Pegões, duas filas de arcos sobrepostas em que a arcaria de volta inteira superior repousa nos arcos ogivados inferiores.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/Aqueduto%20dos%20Peges%20web.jpg',longitude:'39.608552',latitude:'-8.439092',monument:@m18, beacon:@b18)
# @p19 = Poi.create(name:'Estaus',description:'O edifício, onde funcionou o antigo bazar dos judeus foi encomendado pelo Infante D. Henrique para sua aposentadoria, alojamento e comércio. A complexa construção de dezasseis arcos em ogiva nos dois lados da rua nunca foi concluída.',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/Estaus.jpg',longitude:'39.602247',latitude:'-8.411906',monument:@m19, beacon:@b19)
# @p20 = Poi.create(name:'Levada de Tomar',description:'Sob a designação de Levada de Tomar, identificamos um conjunto edificado com um relevante horizonte cronológico, desde o período medieval, passando pela época moderna, até à época contemporânea.A sua origem remonta aos finais do século XII e, com uma sucessão complexa de contextos espaciais e tecnológicos, a sua actividade de carácter industrial manteve-se até finais do século XX  (e, numa das unidades oficinais daquele conjunto, manteve-se até ao início do século XXI).',image:'http://www.cm-tomar.pt/images/CMT/municipio/imagens/Patrimonio/levada_nuno_miguel_queiroz.jpg',longitude:'39.603618',latitude:'-8.411616',monument:@m20, beacon:@b20)




#@p1 = Poi.create(name:'Charola',description:'charola',image:'image',longitude:'123',latitude:'321',monument:@m1, beacon:@b2)

#@a1 = Access.create(date:)