language: ruby
rvm:
 - 2.3.3
 - jruby
 - rbx-2
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

 script:
   - bundle rake
  # - bin/rake db:migrate rails_env=test
  # - bin/rake